// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: challenges.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChallengeParticipant = `-- name: AddChallengeParticipant :one
INSERT INTO challenge_participants (
    challenge_id,
    user_id
) VALUES (
    $1, $2
)
RETURNING challenge_id, user_id, joined_at
`

type AddChallengeParticipantParams struct {
	ChallengeID pgtype.UUID `json:"challenge_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddChallengeParticipant(ctx context.Context, arg AddChallengeParticipantParams) (ChallengeParticipant, error) {
	row := q.db.QueryRow(ctx, addChallengeParticipant, arg.ChallengeID, arg.UserID)
	var i ChallengeParticipant
	err := row.Scan(&i.ChallengeID, &i.UserID, &i.JoinedAt)
	return i, err
}

const createChallenge = `-- name: CreateChallenge :one
INSERT INTO challenges (
  group_id,
  creator_id,
  title,
  description,
  start_time,
  end_time,
  status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, group_id, creator_id, title, description, start_time, end_time, status, created_at, updated_at
`

type CreateChallengeParams struct {
	GroupID     pgtype.UUID        `json:"group_id"`
	CreatorID   pgtype.UUID        `json:"creator_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	EndTime     pgtype.Timestamptz `json:"end_time"`
	Status      string             `json:"status"`
}

func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, createChallenge,
		arg.GroupID,
		arg.CreatorID,
		arg.Title,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatorID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveChallengeByGroup = `-- name: GetActiveChallengeByGroup :one
SELECT id, group_id, creator_id, title, description, start_time, end_time, status, created_at, updated_at FROM challenges
WHERE group_id = $1 AND status = 'ACTIVE'
LIMIT 1
`

func (q *Queries) GetActiveChallengeByGroup(ctx context.Context, groupID pgtype.UUID) (Challenge, error) {
	row := q.db.QueryRow(ctx, getActiveChallengeByGroup, groupID)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatorID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChallenge = `-- name: GetChallenge :one
SELECT id, group_id, creator_id, title, description, start_time, end_time, status, created_at, updated_at FROM challenges
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetChallenge(ctx context.Context, id pgtype.UUID) (Challenge, error) {
	row := q.db.QueryRow(ctx, getChallenge, id)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatorID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChallengeParticipants = `-- name: ListChallengeParticipants :many
SELECT cp.challenge_id, cp.user_id, cp.joined_at, u.name, u.email
FROM challenge_participants cp
JOIN users u ON cp.user_id = u.id
WHERE cp.challenge_id = $1
`

type ListChallengeParticipantsRow struct {
	ChallengeID pgtype.UUID        `json:"challenge_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
}

func (q *Queries) ListChallengeParticipants(ctx context.Context, challengeID pgtype.UUID) ([]ListChallengeParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listChallengeParticipants, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChallengeParticipantsRow
	for rows.Next() {
		var i ListChallengeParticipantsRow
		if err := rows.Scan(
			&i.ChallengeID,
			&i.UserID,
			&i.JoinedAt,
			&i.Name,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChallengesByGroup = `-- name: ListChallengesByGroup :many
SELECT id, group_id, creator_id, title, description, start_time, end_time, status, created_at, updated_at FROM challenges
WHERE group_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListChallengesByGroupParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListChallengesByGroup(ctx context.Context, arg ListChallengesByGroupParams) ([]Challenge, error) {
	rows, err := q.db.Query(ctx, listChallengesByGroup, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Challenge
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatorID,
			&i.Title,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChallengeStatus = `-- name: UpdateChallengeStatus :one
UPDATE challenges
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, group_id, creator_id, title, description, start_time, end_time, status, created_at, updated_at
`

type UpdateChallengeStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateChallengeStatus(ctx context.Context, arg UpdateChallengeStatusParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, updateChallengeStatus, arg.ID, arg.Status)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatorID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
