// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddChallengeParticipant(ctx context.Context, arg AddChallengeParticipantParams) (ChallengeParticipant, error)
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (GroupMember, error)
	CountVotesByOption(ctx context.Context, challengeID pgtype.UUID) ([]CountVotesByOptionRow, error)
	CreateChallenge(ctx context.Context, arg CreateChallengeParams) (Challenge, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error)
	CreateWithdrawalRequest(ctx context.Context, arg CreateWithdrawalRequestParams) (WithdrawalRequest, error)
	DeleteGroup(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetActiveChallengeByGroup(ctx context.Context, groupID pgtype.UUID) (Challenge, error)
	GetChallenge(ctx context.Context, id pgtype.UUID) (Challenge, error)
	GetGroup(ctx context.Context, id pgtype.UUID) (Group, error)
	GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error)
	GetTransaction(ctx context.Context, id pgtype.UUID) (Transaction, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserBalance(ctx context.Context, userID pgtype.UUID) (pgtype.Numeric, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetVote(ctx context.Context, arg GetVoteParams) (Vote, error)
	GetWithdrawalRequest(ctx context.Context, id pgtype.UUID) (WithdrawalRequest, error)
	ListChallengeParticipants(ctx context.Context, challengeID pgtype.UUID) ([]ListChallengeParticipantsRow, error)
	ListChallengesByGroup(ctx context.Context, arg ListChallengesByGroupParams) ([]Challenge, error)
	ListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]ListGroupMembersRow, error)
	ListGroups(ctx context.Context, arg ListGroupsParams) ([]Group, error)
	ListPendingWithdrawals(ctx context.Context) ([]WithdrawalRequest, error)
	ListTransactionsByUser(ctx context.Context, arg ListTransactionsByUserParams) ([]Transaction, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListVotesByChallenge(ctx context.Context, challengeID pgtype.UUID) ([]ListVotesByChallengeRow, error)
	ListWithdrawalRequests(ctx context.Context, arg ListWithdrawalRequestsParams) ([]WithdrawalRequest, error)
	RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error
	UpdateChallengeStatus(ctx context.Context, arg UpdateChallengeStatusParams) (Challenge, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateWithdrawalStatus(ctx context.Context, arg UpdateWithdrawalStatusParams) (WithdrawalRequest, error)
}

var _ Querier = (*Queries)(nil)
