// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  user_id,
  amount,
  type,
  description
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, user_id, amount, type, description, created_at
`

type CreateTransactionParams struct {
	UserID      pgtype.UUID    `json:"user_id"`
	Amount      pgtype.Numeric `json:"amount"`
	Type        string         `json:"type"`
	Description pgtype.Text    `json:"description"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Type,
		arg.Description,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, user_id, amount, type, description, created_at FROM transactions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransaction(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getUserBalance = `-- name: GetUserBalance :one
SELECT COALESCE(SUM(amount), 0)::DECIMAL
FROM transactions
WHERE user_id = $1
`

func (q *Queries) GetUserBalance(ctx context.Context, userID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getUserBalance, userID)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const listTransactionsByUser = `-- name: ListTransactionsByUser :many
SELECT id, user_id, amount, type, description, created_at FROM transactions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListTransactionsByUser(ctx context.Context, arg ListTransactionsByUserParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
