// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: votes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVotesByOption = `-- name: CountVotesByOption :many
SELECT vote_option, COUNT(*) as count
FROM votes
WHERE challenge_id = $1
GROUP BY vote_option
`

type CountVotesByOptionRow struct {
	VoteOption string `json:"vote_option"`
	Count      int64  `json:"count"`
}

func (q *Queries) CountVotesByOption(ctx context.Context, challengeID pgtype.UUID) ([]CountVotesByOptionRow, error) {
	rows, err := q.db.Query(ctx, countVotesByOption, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountVotesByOptionRow
	for rows.Next() {
		var i CountVotesByOptionRow
		if err := rows.Scan(&i.VoteOption, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createVote = `-- name: CreateVote :one
INSERT INTO votes (
  challenge_id,
  voter_id,
  vote_option
) VALUES (
  $1, $2, $3
)
RETURNING id, challenge_id, voter_id, vote_option, created_at
`

type CreateVoteParams struct {
	ChallengeID pgtype.UUID `json:"challenge_id"`
	VoterID     pgtype.UUID `json:"voter_id"`
	VoteOption  string      `json:"vote_option"`
}

func (q *Queries) CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error) {
	row := q.db.QueryRow(ctx, createVote, arg.ChallengeID, arg.VoterID, arg.VoteOption)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.VoterID,
		&i.VoteOption,
		&i.CreatedAt,
	)
	return i, err
}

const getVote = `-- name: GetVote :one
SELECT id, challenge_id, voter_id, vote_option, created_at FROM votes
WHERE challenge_id = $1 AND voter_id = $2
LIMIT 1
`

type GetVoteParams struct {
	ChallengeID pgtype.UUID `json:"challenge_id"`
	VoterID     pgtype.UUID `json:"voter_id"`
}

func (q *Queries) GetVote(ctx context.Context, arg GetVoteParams) (Vote, error) {
	row := q.db.QueryRow(ctx, getVote, arg.ChallengeID, arg.VoterID)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.VoterID,
		&i.VoteOption,
		&i.CreatedAt,
	)
	return i, err
}

const listVotesByChallenge = `-- name: ListVotesByChallenge :many
SELECT v.id, v.challenge_id, v.voter_id, v.vote_option, v.created_at, u.name as voter_name
FROM votes v
JOIN users u ON v.voter_id = u.id
WHERE v.challenge_id = $1
`

type ListVotesByChallengeRow struct {
	ID          pgtype.UUID        `json:"id"`
	ChallengeID pgtype.UUID        `json:"challenge_id"`
	VoterID     pgtype.UUID        `json:"voter_id"`
	VoteOption  string             `json:"vote_option"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	VoterName   string             `json:"voter_name"`
}

func (q *Queries) ListVotesByChallenge(ctx context.Context, challengeID pgtype.UUID) ([]ListVotesByChallengeRow, error) {
	rows, err := q.db.Query(ctx, listVotesByChallenge, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVotesByChallengeRow
	for rows.Next() {
		var i ListVotesByChallengeRow
		if err := rows.Scan(
			&i.ID,
			&i.ChallengeID,
			&i.VoterID,
			&i.VoteOption,
			&i.CreatedAt,
			&i.VoterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
