// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: withdrawals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWithdrawalRequest = `-- name: CreateWithdrawalRequest :one
INSERT INTO withdrawal_requests (
  user_id,
  amount,
  status
) VALUES (
  $1, $2, 'PENDING'
)
RETURNING id, user_id, amount, status, created_at, updated_at
`

type CreateWithdrawalRequestParams struct {
	UserID pgtype.UUID    `json:"user_id"`
	Amount pgtype.Numeric `json:"amount"`
}

func (q *Queries) CreateWithdrawalRequest(ctx context.Context, arg CreateWithdrawalRequestParams) (WithdrawalRequest, error) {
	row := q.db.QueryRow(ctx, createWithdrawalRequest, arg.UserID, arg.Amount)
	var i WithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWithdrawalRequest = `-- name: GetWithdrawalRequest :one
SELECT id, user_id, amount, status, created_at, updated_at FROM withdrawal_requests
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWithdrawalRequest(ctx context.Context, id pgtype.UUID) (WithdrawalRequest, error) {
	row := q.db.QueryRow(ctx, getWithdrawalRequest, id)
	var i WithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingWithdrawals = `-- name: ListPendingWithdrawals :many
SELECT id, user_id, amount, status, created_at, updated_at FROM withdrawal_requests
WHERE status = 'PENDING'
ORDER BY created_at ASC
`

func (q *Queries) ListPendingWithdrawals(ctx context.Context) ([]WithdrawalRequest, error) {
	rows, err := q.db.Query(ctx, listPendingWithdrawals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WithdrawalRequest
	for rows.Next() {
		var i WithdrawalRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawalRequests = `-- name: ListWithdrawalRequests :many
SELECT id, user_id, amount, status, created_at, updated_at FROM withdrawal_requests
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListWithdrawalRequestsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListWithdrawalRequests(ctx context.Context, arg ListWithdrawalRequestsParams) ([]WithdrawalRequest, error) {
	rows, err := q.db.Query(ctx, listWithdrawalRequests, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WithdrawalRequest
	for rows.Next() {
		var i WithdrawalRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWithdrawalStatus = `-- name: UpdateWithdrawalStatus :one
UPDATE withdrawal_requests
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, amount, status, created_at, updated_at
`

type UpdateWithdrawalStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateWithdrawalStatus(ctx context.Context, arg UpdateWithdrawalStatusParams) (WithdrawalRequest, error) {
	row := q.db.QueryRow(ctx, updateWithdrawalStatus, arg.ID, arg.Status)
	var i WithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
